service: minecraft-bot
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  logRetentionInDays: 1
  memorySize: 128
  timeout: 10
  versionFunctions: false
  environment:
    GUILD_ID: 408081312256098305
    DISCORD_BOT_PUBLIC_KEY: ${env:DISCORD_BOT_PUBLIC_KEY}
    ALGOLIA_APP_ID: ${env:ALGOLIA_APP_ID}
    ALGOLIA_ADMIN_KEY: ${env:ALGOLIA_ADMIN_KEY}
    ALGOLIA_INDEX_NAME: coordinates_index

functions:
  main:
    handler: src/handler.default
    events:
      - http:
          path: minecraft/interaction
          method: POST
          cors: true
    tags:
      service: minecraft
      application: locations-bot

plugins:
  - serverless-bundle