service: minecraft-bot
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  logRetentionInDays: 1
  memorySize: 128
  timeout: 10
  versionFunctions: false
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:GetItem
          Resource: arn:aws:dynamodb:us-east-1:*:table/*
  environment:
    GUILD_ID: 1234567890

functions:
  main:
    handler: src/handler.default
    events:
      - http:
          path: minecraft/interaction
          method: POST
          cors: true
    tags:
      service: minecraft
      application: locations-bot

plugins:
  - serverless-bundle